services:
    discord-bot:
        container_name: raid-manager2
        image: ghcr.io/eineisbxr/raid-manager-image:latest
        ports:
            - "8000:8000"
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
            - ADMIN_ROLE_IDS=${ADMIN_ROLE_IDS}
            - COC_API_TOKEN=${COC_API_TOKEN}
            - DATABASE_URL=${DATABASE_URL}
            - DIRECT_URL=${DIRECT_URL}
