name: publish

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.actor }}/raid-manager-image

jobs:
    publish:
        name: Publish Docker image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - id: toLowerCase
              run: echo "::set-output name=lowerCaseValue::$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')"

            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
                  docker build -t ${{ env.REGISTRY }}/${{ steps.toLowerCase.outputs.lowerCaseValue }} .
                  docker push ${{ env.REGISTRY }}/${{ steps.toLowerCase.outputs.lowerCaseValue }}
    deploy:
        needs: publish
        name: Deploy image
        runs-on: ubuntu-latest

        steps:
            - name: install ssh keys
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            - name: connect and pull
              run: |
                  ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'docker compose up -d'
            - name: cleanup
              run: |
                  rm -rf ~/.ssh
