name: publish and deploy

on:
    push:
        branches: ["main"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository_owner }}/raid-manager-image:latest

jobs:
    publish:
        name: Publish Docker image
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - id: toLowerCase
              run: echo "lowerCaseValue=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.PAT }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/arm64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.lowerCaseValue }}

    deploy:
        needs: publish
        name: Deploy image
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: install ssh keys
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
                  chmod 600 ~/.ssh/deploy_key
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
            - name: connect and pull
              run: |
                  ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ./github_autodeploy && docker kill raid-manager && docker rm raid-manager && docker image rm ghcr.io/eineisbxr/raid-manager-image:latest && docker compose up -d'
            - name: cleanup
              run: |
                  rm -rf ~/.ssh
